### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError: limit must be a scalar, not shape [1] [Op:Range] name: range/ evaluting generation at epoch 64

### ISSUE THREAD

**Issue by hantongyou** [google-research/crest#4]
### _Here is the information of error:_
evaluting generation at epoch 64                 
acc 0.655
per_class_recall [0.978 0.994 0.858 0.789 0.806 0.52  0.615 0.547 0.222 0.224]
per_class_precision [0.4882676  0.5748988  0.63697106 0.52113605 0.72743684 0.83467096
 0.94180703 0.9513044  1.         0.99115044]
confusion_matrix [[978.   3.   9.   7.   2.   1.   0.   0.   0.   0.]
 [  5. 994.   0.   0.   0.   1.   0.   0.   0.   0.]
 [ 64.   2. 858.  26.  27.  15.   7.   1.   0.   0.]
 [ 48.   7.  69. 789.  28.  39.  13.   7.   0.   0.]
 [ 38.   0.  70.  62. 806.   7.  10.   7.   0.   0.]
 [ 19.   2.  84. 316.  43. 520.   4.  12.   0.   0.]
 [ 38.   7. 147. 152.  34.   7. 615.   0.   0.   0.]
 [ 67.   2.  75. 116. 160.  31.   2. 547.   0.   0.]
 [584. 142.  27.  15.   5.   1.   2.   0. 222.   2.]
 [162. 570.   8.  31.   3.   1.   0.   1.   0. 224.]]
Traceback (most recent call last):               
  File "/userdata/anaconda3/envs/hty-crest/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/userdata/anaconda3/envs/hty-crest/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/userdata/hty/crest-master/train_and_eval_loop.py", line 200, in <module>
    app.run(main)
  File "/userdata/anaconda3/envs/hty-crest/lib/python3.7/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/userdata/anaconda3/envs/hty-crest/lib/python3.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/userdata/hty/crest-master/train_and_eval_loop.py", line 196, in main
    trainer.train_generations()
  File "/userdata/hty/crest-master/util/semisup.py", line 155, in train_generations
    pseudo_label_list = self.eval()
  File "/userdata/hty/crest-master/util/semisup.py", line 264, in eval
    pseudo_label_list = self.get_pseudo_label_list(unlab_scores)
  File "/userdata/hty/crest-master/util/semisup.py", line 292, in get_pseudo_label_list
    idx = tf.range(y_pred.shape)
  File "/userdata/anaconda3/envs/hty-crest/lib/python3.7/site-packages/tensorflow_core/python/ops/math_ops.py", line 1438, in range
    return gen_math_ops._range(start, limit, delta, name=name)
  File "/userdata/anaconda3/envs/hty-crest/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_math_ops.py", line 7790, in _range
    _six.raise_from(_core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: limit must be a scalar, not shape [1] [Op:Range] name: range/
evaluting generation at epoch 64
acc 0.687

Besides, there is nothing in the $RESULT directory, how to fix this?

**Comment by hantongyou** [comment]
Okay...I think I have found the problem, in /util/semisup.py,change the code from:
`  def get_pseudo_label_list(self, scores):
    """Generate per class pseudo label list."""
    y_pred = tf.argmax(scores, axis=1)
    y_score = tf.math.reduce_max(scores, axis=1)
    idx = tf.range(y_pred.shape)`
to
`  def get_pseudo_label_list(self, scores):
    """Generate per class pseudo label list."""
    y_pred = tf.argmax(scores, axis=1)
    y_score = tf.math.reduce_max(scores, axis=1)
    idx = tf.range(y_pred.shape[0])#changed here`
